export default [
  {
    type: 'style',
    name: 'outline',
    title: 'Outline',
    children: [
      {
        type: 'category',
        name: 'Navigation',
        title: 'Navigation',
        children: [
          { type: 'component', title: 'Home', name: 'HomeIcon' },
          { type: 'component', title: 'Apps', name: 'AppsIcon' },
          { type: 'component', title: 'TriangleDown', name: 'TriangleDownIcon' },
          { type: 'component', title: 'TriangleLeft', name: 'TriangleLeftIcon' },
          { type: 'component', title: 'TriangleRight', name: 'TriangleRightIcon' },
          { type: 'component', title: 'ShellWindowMaximize', name: 'ShellWindowMaximizeIcon' },
          { type: 'component', title: 'TriangleUp', name: 'TriangleUpIcon' },
          { type: 'component', title: 'Sort', name: 'SortIcon' },
          { type: 'component', title: 'Up', name: 'UpIcon' },
          { type: 'component', title: 'Down', name: 'DownIcon' },
          { type: 'component', title: 'Left', name: 'LeftIcon' },
          { type: 'component', title: 'Right', name: 'RightIcon' },
          { type: 'component', title: 'DoubleArrowUp', name: 'DoubleArrowUpIcon' },
          { type: 'component', title: 'DoubleArrowDown', name: 'DoubleArrowDownIcon' },
          { type: 'component', title: 'DoubleArrowLeft', name: 'DoubleArrowLeftIcon' },
          { type: 'component', title: 'DoubleArrowRight', name: 'DoubleArrowRightIcon' },
          { type: 'component', title: 'ArrowUp', name: 'ArrowUpIcon' },
          { type: 'component', title: 'ArrowDown', name: 'ArrowDownIcon' },
          { type: 'component', title: 'ArrowLeft', name: 'ArrowLeftIcon' },
          { type: 'component', title: 'MenuThwartwise', name: 'MenuThwartwiseIcon' },
          { type: 'component', title: 'Menu2', name: 'Menu2Icon' },
          { type: 'component', title: 'ArrowRight', name: 'ArrowRightIcon' },
          { type: 'component', title: 'MenuEndways', name: 'MenuEndwaysIcon' },
          { type: 'component', title: 'CloseSmall', name: 'CloseSmallIcon' },
          { type: 'component', title: 'OpenNew', name: 'OpenNewIcon' },
          { type: 'component', title: 'ShellWindowMinimize', name: 'ShellWindowMinimizeIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Notice',
        title: 'Notice',
        children: [
          { type: 'component', title: 'RemindClose', name: 'RemindCloseIcon' },
          { type: 'component', title: 'WifiAbnormal', name: 'WifiAbnormalIcon' },
          { type: 'component', title: 'Question', name: 'QuestionIcon' },
          { type: 'component', title: 'Remind', name: 'RemindIcon' },
          { type: 'component', title: 'AddOne', name: 'AddOneIcon' },
          { type: 'component', title: 'Check', name: 'CheckIcon' },
          { type: 'component', title: 'CircleMore', name: 'CircleMoreIcon' },
          { type: 'component', title: 'More', name: 'MoreIcon' },
          { type: 'component', title: 'Minus', name: 'MinusIcon' },
          { type: 'component', title: 'CircleAdd', name: 'CircleAddIcon' },
          { type: 'component', title: 'TriangleWarning', name: 'TriangleWarningIcon' },
          { type: 'component', title: 'Exclamation', name: 'ExclamationIcon' },
          { type: 'component', title: 'CircleInformation', name: 'CircleInformationIcon' },
          { type: 'component', title: 'CircleClose', name: 'CircleCloseIcon' },
          { type: 'component', title: 'CircleStar', name: 'CircleStarIcon' },
          { type: 'component', title: 'CircleSucceed', name: 'CircleSucceedIcon' },
          { type: 'component', title: 'CircleWarning', name: 'CircleWarningIcon' },
          { type: 'component', title: 'Star', name: 'StarIcon' },
          { type: 'component', title: 'CircleHelp', name: 'CircleHelpIcon' },
          { type: 'component', title: 'Disable', name: 'DisableIcon' },
          { type: 'component', title: 'Wifi', name: 'WifiIcon' },
          { type: 'component', title: 'WifiClose', name: 'WifiCloseIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Action',
        title: 'Action',
        children: [
          { type: 'component', title: 'Pin', name: 'PinIcon' },
          { type: 'component', title: 'ThumbDown', name: 'ThumbDownIcon' },
          { type: 'component', title: 'Clear', name: 'ClearIcon' },
          { type: 'component', title: 'MapLocation', name: 'MapLocationIcon' },
          { type: 'component', title: 'ViewOff', name: 'ViewOffIcon' },
          { type: 'component', title: 'Edit', name: 'EditIcon' },
          { type: 'component', title: 'Send', name: 'SendIcon' },
          { type: 'component', title: 'MoveUp', name: 'MoveUpIcon' },
          { type: 'component', title: 'ThumbUp', name: 'ThumbUpIcon' },
          { type: 'component', title: 'PinPre', name: 'PinPreIcon' },
          { type: 'component', title: 'View', name: 'ViewIcon' },
          { type: 'component', title: 'Filter', name: 'FilterIcon' },
          { type: 'component', title: 'Search', name: 'SearchIcon' },
          { type: 'component', title: 'Urgency', name: 'UrgencyIcon' },
          { type: 'component', title: 'Clothes', name: 'ClothesIcon' },
          { type: 'component', title: 'Microphone', name: 'MicrophoneIcon' },
          { type: 'component', title: 'BatchAdd', name: 'BatchAddIcon' },
          { type: 'component', title: 'Phone', name: 'PhoneIcon' },
          { type: 'component', title: 'Decorate', name: 'DecorateIcon' },
          { type: 'component', title: 'CopyOne', name: 'CopyOneIcon' },
          { type: 'component', title: 'Delete', name: 'DeleteIcon' },
          { type: 'component', title: 'Print', name: 'PrintIcon' },
          { type: 'component', title: 'BatchCheck', name: 'BatchCheckIcon' },
          { type: 'component', title: 'CheckCorrect', name: 'CheckCorrectIcon' },
          { type: 'component', title: 'CheckDisabled', name: 'CheckDisabledIcon' },
          { type: 'component', title: 'Checkbox', name: 'CheckboxIcon' },
          { type: 'component', title: 'RadioUnselected', name: 'RadioUnselectedIcon' },
          { type: 'component', title: 'RadioSelected', name: 'RadioSelectedIcon' },
          { type: 'component', title: 'Save', name: 'SaveIcon' },
          { type: 'component', title: 'SaveAs', name: 'SaveAsIcon' },
          { type: 'component', title: 'Rollback', name: 'RollbackIcon' },
          { type: 'component', title: 'Swerve', name: 'SwerveIcon' },
          { type: 'component', title: 'Paste', name: 'PasteIcon' },
          { type: 'component', title: 'FormatPainter', name: 'FormatPainterIcon' },
          { type: 'component', title: 'Setting', name: 'SettingIcon' },
          { type: 'component', title: 'SettingSearch', name: 'SettingSearchIcon' },
          { type: 'component', title: 'AddChat', name: 'AddChatIcon' },
          { type: 'component', title: 'AddChatTwo', name: 'AddChatTwoIcon' },
          { type: 'component', title: 'Power', name: 'PowerIcon' },
          { type: 'component', title: 'InfuseOne', name: 'InfuseOneIcon' },
          { type: 'component', title: 'Submit', name: 'SubmitIcon' },
          { type: 'component', title: 'Scan', name: 'ScanIcon' },
          { type: 'component', title: 'Control', name: 'ControlIcon' },
          { type: 'component', title: 'Translate', name: 'TranslateIcon' },
          { type: 'component', title: 'Refresh', name: 'RefreshIcon' },
          { type: 'component', title: 'RefreshDoing', name: 'RefreshDoingIcon' },
          { type: 'component', title: 'RefreshDone', name: 'RefreshDoneIcon' },
          { type: 'component', title: 'Share', name: 'ShareIcon' },
          { type: 'component', title: 'Uploading', name: 'UploadingIcon' },
          { type: 'component', title: 'Export', name: 'ExportIcon' },
          { type: 'component', title: 'Download', name: 'DownloadIcon' },
          { type: 'component', title: 'InfuseTwo', name: 'InfuseTwoIcon' },
          { type: 'component', title: 'Switch', name: 'SwitchIcon' },
          { type: 'component', title: 'ToTop', name: 'ToTopIcon' },
          { type: 'component', title: 'ToBottom', name: 'ToBottomIcon' },
          { type: 'component', title: 'MoveDown', name: 'MoveDownIcon' },
          { type: 'component', title: 'Top', name: 'TopIcon' },
          { type: 'component', title: 'Undo', name: 'UndoIcon' },
          { type: 'component', title: 'Goto', name: 'GotoIcon' },
          { type: 'component', title: 'AmountUpTwo', name: 'AmountUpTwoIcon' },
          { type: 'component', title: 'AmountDownTwo', name: 'AmountDownTwoIcon' },
          { type: 'component', title: 'AmountDown', name: 'AmountDownIcon' },
          { type: 'component', title: 'AmountUp', name: 'AmountUpIcon' },
          { type: 'component', title: 'SortFilter', name: 'SortFilterIcon' },
          { type: 'component', title: 'SortAToZ', name: 'SortAToZIcon' },
          { type: 'component', title: 'Link', name: 'LinkIcon' },
          { type: 'component', title: 'Drag', name: 'DragIcon' },
          { type: 'component', title: 'Unlink', name: 'UnlinkIcon' },
          { type: 'component', title: 'SortZToA', name: 'SortZToAIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Control',
        title: 'Control',
        children: [
          { type: 'component', title: 'ScreenFull', name: 'ScreenFullIcon' },
          { type: 'component', title: 'ScreenOff', name: 'ScreenOffIcon' },
          { type: 'component', title: 'Move', name: 'MoveIcon' },
          { type: 'component', title: 'Pointer', name: 'PointerIcon' },
          { type: 'component', title: 'Coverage', name: 'CoverageIcon' },
          { type: 'component', title: 'SurfaceFront', name: 'SurfaceFrontIcon' },
          { type: 'component', title: 'SurfaceTop', name: 'SurfaceTopIcon' },
          { type: 'component', title: 'SurfaceLeft', name: 'SurfaceLeftIcon' },
          { type: 'component', title: 'SurfaceRight', name: 'SurfaceRightIcon' },
          { type: 'component', title: 'Find', name: 'FindIcon' },
          { type: 'component', title: 'Text', name: 'TextIcon' },
          { type: 'component', title: 'TopAlign', name: 'TopAlignIcon' },
          { type: 'component', title: 'BottomAlign', name: 'BottomAlignIcon' },
          { type: 'component', title: 'LeftAlign', name: 'LeftAlignIcon' },
          { type: 'component', title: 'RightAlign', name: 'RightAlignIcon' },
          { type: 'component', title: 'BackSquare', name: 'BackSquareIcon' },
          { type: 'component', title: 'LeftSquare', name: 'LeftSquareIcon' },
          { type: 'component', title: 'RightSquare', name: 'RightSquareIcon' },
          { type: 'component', title: 'FrontSquare', name: 'FrontSquareIcon' },
          { type: 'component', title: 'CopyTwo', name: 'CopyTwoIcon' },
          { type: 'component', title: 'AdjustHight', name: 'AdjustHightIcon' },
          { type: 'component', title: 'HightLessen', name: 'HightLessenIcon' },
          { type: 'component', title: 'AdjustWidth', name: 'AdjustWidthIcon' },
          { type: 'component', title: 'VerticalSplit', name: 'VerticalSplitIcon' },
          { type: 'component', title: 'VerticalCenter', name: 'VerticalCenterIcon' },
          { type: 'component', title: 'CenterHorizontally', name: 'CenterHorizontallyIcon' },
          { type: 'component', title: 'Keyboard', name: 'KeyboardIcon' },
          { type: 'component', title: 'ZoomOut', name: 'ZoomOutIcon' },
          { type: 'component', title: 'ZoomIn', name: 'ZoomInIcon' },
          { type: 'component', title: 'Volume', name: 'VolumeIcon' },
          { type: 'component', title: 'VolumeMute', name: 'VolumeMuteIcon' },
          { type: 'component', title: 'VolumeUp', name: 'VolumeUpIcon' },
          { type: 'component', title: 'VolumeDown', name: 'VolumeDownIcon' },
          { type: 'component', title: 'Play', name: 'PlayIcon' },
          { type: 'component', title: 'Stop', name: 'StopIcon' },
          { type: 'component', title: 'Suspend', name: 'SuspendIcon' },
          { type: 'component', title: 'AlignTxtLeft', name: 'AlignTxtLeftIcon' },
          { type: 'component', title: 'AlignTxtRight', name: 'AlignTxtRightIcon' },
          { type: 'component', title: 'AlignTxtCenter', name: 'AlignTxtCenterIcon' },
          { type: 'component', title: 'DensityL', name: 'DensityLIcon' },
          { type: 'component', title: 'DensityM', name: 'DensityMIcon' },
          { type: 'component', title: 'DensityS', name: 'DensitySIcon' },
          { type: 'component', title: 'FitScreen', name: 'FitScreenIcon' },
          { type: 'component', title: 'AlignTxtBoth', name: 'AlignTxtBothIcon' },
          { type: 'component', title: 'RotationLeft', name: 'RotationLeftIcon' },
          { type: 'component', title: 'RotationRight', name: 'RotationRightIcon' },
          { type: 'component', title: 'OneToOne', name: 'OneToOneIcon' },
          { type: 'component', title: 'RowHeightS', name: 'RowHeightSIcon' },
          { type: 'component', title: 'RowHeightM', name: 'RowHeightMIcon' },
          { type: 'component', title: 'RowHeightL', name: 'RowHeightLIcon' },
          { type: 'component', title: 'Clockwise90', name: 'Clockwise90Icon' },
          { type: 'component', title: 'Anticlockwise90', name: 'Anticlockwise90Icon' },
          { type: 'component', title: 'LinecapButt', name: 'LinecapButtIcon' },
          { type: 'component', title: 'LinecapSquare', name: 'LinecapSquareIcon' },
          { type: 'component', title: 'LinecapRound', name: 'LinecapRoundIcon' },
          { type: 'component', title: 'LinejoinMiter', name: 'LinejoinMiterIcon' },
          { type: 'component', title: 'LinejoinBevel', name: 'LinejoinBevelIcon' },
          { type: 'component', title: 'LinejoinRound', name: 'LinejoinRoundIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Data',
        title: 'Data',
        children: [
          { type: 'component', title: 'Lightning', name: 'LightningIcon' },
          { type: 'component', title: 'PieTwo', name: 'PieTwoIcon' },
          { type: 'component', title: 'Data', name: 'DataIcon' },
          { type: 'component', title: 'Percent', name: 'PercentIcon' },
          { type: 'component', title: 'LineChart', name: 'LineChartIcon' },
          { type: 'component', title: 'Tree', name: 'TreeIcon' },
          { type: 'component', title: 'ThermoDynamic', name: 'ThermoDynamicIcon' },
          { type: 'component', title: 'Measure', name: 'MeasureIcon' },
          { type: 'component', title: 'Compiling', name: 'CompilingIcon' },
          { type: 'component', title: 'AreaChart', name: 'AreaChartIcon' },
          { type: 'component', title: 'Bar', name: 'BarIcon' },
          { type: 'component', title: 'Column', name: 'ColumnIcon' },
          { type: 'component', title: 'ColumnLine', name: 'ColumnLineIcon' },
          { type: 'component', title: 'WordCloud', name: 'WordCloudIcon' },
          { type: 'component', title: 'Table', name: 'TableIcon' },
          { type: 'component', title: 'PieOne', name: 'PieOneIcon' },
          { type: 'component', title: 'Annular', name: 'AnnularIcon' },
          { type: 'component', title: 'RadarChart', name: 'RadarChartIcon' },
          { type: 'component', title: 'DataScreen', name: 'DataScreenIcon' },
          { type: 'component', title: 'Constitute', name: 'ConstituteIcon' },
          { type: 'component', title: 'Database', name: 'DatabaseIcon' },
          { type: 'component', title: 'Decimal', name: 'DecimalIcon' },
          { type: 'component', title: 'ScatterDiagram', name: 'ScatterDiagramIcon' },
          { type: 'component', title: 'Number', name: 'NumberIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Common',
        title: 'Common',
        children: [
          { type: 'component', title: 'Lock', name: 'LockIcon' },
          { type: 'component', title: 'Unlock', name: 'UnlockIcon' },
          { type: 'component', title: 'SandGlass', name: 'SandGlassIcon' },
          { type: 'component', title: 'TimeOne', name: 'TimeOneIcon' },
          { type: 'component', title: 'Leaf', name: 'LeafIcon' },
          { type: 'component', title: 'PackingBox', name: 'PackingBoxIcon' },
          { type: 'component', title: 'AmountYuan', name: 'AmountYuanIcon' },
          { type: 'component', title: 'Purse', name: 'PurseIcon' },
          { type: 'component', title: 'AmountDollar', name: 'AmountDollarIcon' },
          { type: 'component', title: 'Deal', name: 'DealIcon' },
          { type: 'component', title: 'Education', name: 'EducationIcon' },
          { type: 'component', title: 'ShoppingBag', name: 'ShoppingBagIcon' },
          { type: 'component', title: 'Basket', name: 'BasketIcon' },
          { type: 'component', title: 'Bed', name: 'BedIcon' },
          { type: 'component', title: 'Soup', name: 'SoupIcon' },
          { type: 'component', title: 'Rice', name: 'RiceIcon' },
          { type: 'component', title: 'Bbq', name: 'BbqIcon' },
          { type: 'component', title: 'Camera', name: 'CameraIcon' },
          { type: 'component', title: 'BarCode', name: 'BarCodeIcon' },
          { type: 'component', title: 'HandShake', name: 'HandShakeIcon' },
          { type: 'component', title: 'Flag', name: 'FlagIcon' },
          { type: 'component', title: 'Motorcycle', name: 'MotorcycleIcon' },
          { type: 'component', title: 'Shield', name: 'ShieldIcon' },
          { type: 'component', title: 'Vip', name: 'VipIcon' },
          { type: 'component', title: 'Calculator', name: 'CalculatorIcon' },
          { type: 'component', title: 'HeavySnow', name: 'HeavySnowIcon' },
          { type: 'component', title: 'Haze', name: 'HazeIcon' },
          { type: 'component', title: 'Sand', name: 'SandIcon' },
          { type: 'component', title: 'Music', name: 'MusicIcon' },
          { type: 'component', title: 'Pad', name: 'PadIcon' },
          { type: 'component', title: 'Mobile', name: 'MobileIcon' },
          { type: 'component', title: 'Computer', name: 'ComputerIcon' },
          { type: 'component', title: 'Building', name: 'BuildingIcon' },
          { type: 'component', title: 'Fire', name: 'FireIcon' },
          { type: 'component', title: 'Gift', name: 'GiftIcon' },
          { type: 'component', title: 'Label', name: 'LabelIcon' },
          { type: 'component', title: 'Map', name: 'MapIcon' },
          { type: 'component', title: 'Location', name: 'LocationIcon' },
          { type: 'component', title: 'Park', name: 'ParkIcon' },
          { type: 'component', title: 'Hospital', name: 'HospitalIcon' },
          { type: 'component', title: 'Chips', name: 'ChipsIcon' },
          { type: 'component', title: 'Equipment', name: 'EquipmentIcon' },
          { type: 'component', title: 'PlaceOrder', name: 'PlaceOrderIcon' },
          { type: 'component', title: 'Chef', name: 'ChefIcon' },
          { type: 'component', title: 'Sunny', name: 'SunnyIcon' },
          { type: 'component', title: 'Cloudy', name: 'CloudyIcon' },
          { type: 'component', title: 'LightRain', name: 'LightRainIcon' },
          { type: 'component', title: 'HeavyRain', name: 'HeavyRainIcon' },
          { type: 'component', title: 'LightSnow', name: 'LightSnowIcon' },
          { type: 'component', title: 'OnlineGateway', name: 'OnlineGatewayIcon' },
          { type: 'component', title: 'Monitoring', name: 'MonitoringIcon' },
          { type: 'component', title: 'BadgeNew', name: 'BadgeNewIcon' },
          { type: 'component', title: 'BadgePromotion', name: 'BadgePromotionIcon' },
          { type: 'component', title: 'Service', name: 'ServiceIcon' },
          { type: 'component', title: 'ShoppingCart', name: 'ShoppingCartIcon' },
          { type: 'component', title: 'CheckStand', name: 'CheckStandIcon' },
          { type: 'component', title: 'Store', name: 'StoreIcon' },
          { type: 'component', title: 'House', name: 'HouseIcon' },
          { type: 'component', title: 'Calendar', name: 'CalendarIcon' },
          { type: 'component', title: 'Stamp', name: 'StampIcon' },
          { type: 'component', title: 'Picture', name: 'PictureIcon' },
          { type: 'component', title: 'PictureOff', name: 'PictureOffIcon' },
          { type: 'component', title: 'Folder', name: 'FolderIcon' },
          { type: 'component', title: 'QrCode', name: 'QrCodeIcon' },
          { type: 'component', title: 'Gather', name: 'GatherIcon' },
          { type: 'component', title: 'Puzzle', name: 'PuzzleIcon' },
          { type: 'component', title: 'Comments', name: 'CommentsIcon' },
          { type: 'component', title: 'Coupon', name: 'CouponIcon' },
          { type: 'component', title: 'List', name: 'ListIcon' },
          { type: 'component', title: 'TimeTwo', name: 'TimeTwoIcon' },
          { type: 'component', title: 'Oclock', name: 'OclockIcon' },
          { type: 'component', title: 'OfflineGateway', name: 'OfflineGatewayIcon' },
          { type: 'component', title: 'FolderFiles', name: 'FolderFilesIcon' },
          { type: 'component', title: 'Earth', name: 'EarthIcon' },
          { type: 'component', title: 'PushMgt', name: 'PushMgtIcon' },
          { type: 'component', title: 'EmailSend', name: 'EmailSendIcon' },
          { type: 'component', title: 'User', name: 'UserIcon' },
          { type: 'component', title: 'UserCrowd', name: 'UserCrowdIcon' },
          { type: 'component', title: 'UserPortrayal', name: 'UserPortrayalIcon' },
          { type: 'component', title: 'UserBlack', name: 'UserBlackIcon' },
          { type: 'component', title: 'UserWhite', name: 'UserWhiteIcon' },
          { type: 'component', title: 'UserSilence', name: 'UserSilenceIcon' },
          { type: 'component', title: 'UserLike', name: 'UserLikeIcon' },
          { type: 'component', title: 'UserLeave', name: 'UserLeaveIcon' },
          { type: 'component', title: 'UserAll', name: 'UserAllIcon' },
          { type: 'component', title: 'UserNew', name: 'UserNewIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Retail',
        title: 'Retail',
        children: [
          { type: 'component', title: 'Consume', name: 'ConsumeIcon' },
          { type: 'component', title: 'VipConsume', name: 'VipConsumeIcon' },
          { type: 'component', title: 'Rail', name: 'RailIcon' },
          { type: 'component', title: 'Integral', name: 'IntegralIcon' },
          { type: 'component', title: 'IntegralDistribute', name: 'IntegralDistributeIcon' },
          { type: 'component', title: 'Picking', name: 'PickingIcon' },
          { type: 'component', title: 'Distribution', name: 'DistributionIcon' },
          { type: 'component', title: 'Goods', name: 'GoodsIcon' },
          { type: 'component', title: 'WarehousePre', name: 'WarehousePreIcon' },
          { type: 'component', title: 'Warehouse', name: 'WarehouseIcon' },
          { type: 'component', title: 'Inventory', name: 'InventoryIcon' },
          { type: 'component', title: 'Replenishment', name: 'ReplenishmentIcon' },
          { type: 'component', title: 'Path', name: 'PathIcon' },
          { type: 'component', title: 'Shelf', name: 'ShelfIcon' },
          { type: 'component', title: 'Management', name: 'ManagementIcon' },
          { type: 'component', title: 'Overtime', name: 'OvertimeIcon' },
          { type: 'component', title: 'Scale', name: 'ScaleIcon' },
          { type: 'component', title: 'SalesReturn', name: 'SalesReturnIcon' },
          { type: 'component', title: 'ManagementStockout', name: 'ManagementStockoutIcon' },
          { type: 'component', title: 'ShelfUp', name: 'ShelfUpIcon' },
          { type: 'component', title: 'ShelfDown', name: 'ShelfDownIcon' },
          { type: 'component', title: 'TimingShelfDown', name: 'TimingShelfDownIcon' },
          { type: 'component', title: 'ProcessMode', name: 'ProcessModeIcon' },
          { type: 'component', title: 'GoodsSearch', name: 'GoodsSearchIcon' },
          { type: 'component', title: 'PickingGuidance', name: 'PickingGuidanceIcon' },
          { type: 'component', title: 'PickingPath', name: 'PickingPathIcon' },
          { type: 'component', title: 'Operation', name: 'OperationIcon' },
          { type: 'component', title: 'Marketing', name: 'MarketingIcon' },
          { type: 'component', title: 'WarehouseInto', name: 'WarehouseIntoIcon' },
          { type: 'component', title: 'OutOfWarehouse', name: 'OutOfWarehouseIcon' },
          { type: 'component', title: 'Marketplace', name: 'MarketplaceIcon' },
          { type: 'component', title: 'Incubator', name: 'IncubatorIcon' },
          { type: 'component', title: 'ToggleWarehouseX', name: 'ToggleWarehouseXIcon' },
          { type: 'component', title: 'ToggleWarehouseY', name: 'ToggleWarehouseYIcon' },
        ],
      },
      {
        type: 'category',
        name: 'File',
        title: 'File',
        children: [
          { type: 'component', title: 'FileCsv', name: 'FileCsvIcon' },
          { type: 'component', title: 'FileRar', name: 'FileRarIcon' },
          { type: 'component', title: 'FilePpt', name: 'FilePptIcon' },
          { type: 'component', title: 'FilePdf', name: 'FilePdfIcon' },
          { type: 'component', title: 'FileMov', name: 'FileMovIcon' },
          { type: 'component', title: 'FileMp3', name: 'FileMp3Icon' },
          { type: 'component', title: 'FileJpg', name: 'FileJpgIcon' },
          { type: 'component', title: 'FileAvi', name: 'FileAviIcon' },
          { type: 'component', title: 'FileTxt', name: 'FileTxtIcon' },
          { type: 'component', title: 'FileMp4', name: 'FileMp4Icon' },
          { type: 'component', title: 'FileDoc', name: 'FileDocIcon' },
          { type: 'component', title: 'FileCdr', name: 'FileCdrIcon' },
          { type: 'component', title: 'FilePng', name: 'FilePngIcon' },
          { type: 'component', title: 'WorkOrderAppointment', name: 'WorkOrderAppointmentIcon' },
          { type: 'component', title: 'WorkOrderCheck', name: 'WorkOrderCheckIcon' },
          { type: 'component', title: 'Order', name: 'OrderIcon' },
          { type: 'component', title: 'OrderIntegral', name: 'OrderIntegralIcon' },
          { type: 'component', title: 'OrderAbnormal', name: 'OrderAbnormalIcon' },
          { type: 'component', title: 'OrderDone', name: 'OrderDoneIcon' },
          { type: 'component', title: 'OrderEdit', name: 'OrderEditIcon' },
          { type: 'component', title: 'FileZip', name: 'FileZipIcon' },
          { type: 'component', title: 'FileXls', name: 'FileXlsIcon' },
          { type: 'component', title: 'WorkOrderAbnormal', name: 'WorkOrderAbnormalIcon' },
          { type: 'component', title: 'WorkingOdd', name: 'WorkingOddIcon' },
          { type: 'component', title: 'Report', name: 'ReportIcon' },
          { type: 'component', title: 'Contract', name: 'ContractIcon' },
          { type: 'component', title: 'OrderClose', name: 'OrderCloseIcon' },
          { type: 'component', title: 'ContractExclamation', name: 'ContractExclamationIcon' },
          { type: 'component', title: 'ContractAcross', name: 'ContractAcrossIcon' },
          { type: 'component', title: 'WorkOrder', name: 'WorkOrderIcon' },
          { type: 'component', title: 'ComputerExclamation', name: 'ComputerExclamationIcon' },
          { type: 'component', title: 'ComputerAcross', name: 'ComputerAcrossIcon' },
          { type: 'component', title: 'FileMovie', name: 'FileMovieIcon' },
          { type: 'component', title: 'WorkOrderInfo', name: 'WorkOrderInfoIcon' },
          { type: 'component', title: 'FileImport', name: 'FileImportIcon' },
          { type: 'component', title: 'FileExport', name: 'FileExportIcon' },
          { type: 'component', title: 'Attachments', name: 'AttachmentsIcon' },
        ],
      },
    ],
  },
  {
    type: 'style',
    name: 'filled',
    title: 'Solid',
    children: [
      {
        type: 'category',
        name: 'Navigation',
        title: 'Navigation',
        children: [
          { type: 'component', title: 'HomeFilled', name: 'HomeFilledIcon' },
          { type: 'component', title: 'AppsFilled', name: 'AppsFilledIcon' },
          { type: 'component', title: 'TriangleDownFilled', name: 'TriangleDownFilledIcon' },
          { type: 'component', title: 'TriangleLeftFilled', name: 'TriangleLeftFilledIcon' },
          { type: 'component', title: 'TriangleRightFilled', name: 'TriangleRightFilledIcon' },
          { type: 'component', title: 'ShellWindowMaximizeFilled', name: 'ShellWindowMaximizeFilledIcon' },
          { type: 'component', title: 'TriangleUpFilled', name: 'TriangleUpFilledIcon' },
          { type: 'component', title: 'SortFilled', name: 'SortFilledIcon' },
          { type: 'component', title: 'UpFilled', name: 'UpFilledIcon' },
          { type: 'component', title: 'DownFilled', name: 'DownFilledIcon' },
          { type: 'component', title: 'LeftFilled', name: 'LeftFilledIcon' },
          { type: 'component', title: 'DoubleArrowUpFilled', name: 'DoubleArrowUpFilledIcon' },
          { type: 'component', title: 'DoubleArrowDownFilled', name: 'DoubleArrowDownFilledIcon' },
          { type: 'component', title: 'DoubleArrowLeftFilled', name: 'DoubleArrowLeftFilledIcon' },
          { type: 'component', title: 'DoubleArrowRightFilled', name: 'DoubleArrowRightFilledIcon' },
          { type: 'component', title: 'ArrowUpFilled', name: 'ArrowUpFilledIcon' },
          { type: 'component', title: 'ArrowDownFilled', name: 'ArrowDownFilledIcon' },
          { type: 'component', title: 'ArrowLeftFilled', name: 'ArrowLeftFilledIcon' },
          { type: 'component', title: 'MenuThwartwiseFilled', name: 'MenuThwartwiseFilledIcon' },
          { type: 'component', title: 'Menu2Filled', name: 'Menu2FilledIcon' },
          { type: 'component', title: 'ArrowRightFilled', name: 'ArrowRightFilledIcon' },
          { type: 'component', title: 'MenuEndwaysFilled', name: 'MenuEndwaysFilledIcon' },
          { type: 'component', title: 'CloseSmallFilled', name: 'CloseSmallFilledIcon' },
          { type: 'component', title: 'OpenNewFilled', name: 'OpenNewFilledIcon' },
          { type: 'component', title: 'ShellWindowMinimizeFilled', name: 'ShellWindowMinimizeFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Notice',
        title: 'Notice',
        children: [
          { type: 'component', title: 'RemindCloseFilled', name: 'RemindCloseFilledIcon' },
          { type: 'component', title: 'WifiAbnormalFilled', name: 'WifiAbnormalFilledIcon' },
          { type: 'component', title: 'QuestionFilled', name: 'QuestionFilledIcon' },
          { type: 'component', title: 'RemindFilled', name: 'RemindFilledIcon' },
          { type: 'component', title: 'AddOneFilled', name: 'AddOneFilledIcon' },
          { type: 'component', title: 'CheckFilled', name: 'CheckFilledIcon' },
          { type: 'component', title: 'CircleMoreFilled', name: 'CircleMoreFilledIcon' },
          { type: 'component', title: 'MoreFilled', name: 'MoreFilledIcon' },
          { type: 'component', title: 'MinusFilled', name: 'MinusFilledIcon' },
          { type: 'component', title: 'CircleAddFilled', name: 'CircleAddFilledIcon' },
          { type: 'component', title: 'TriangleWarningFilled', name: 'TriangleWarningFilledIcon' },
          { type: 'component', title: 'ExclamationFilled', name: 'ExclamationFilledIcon' },
          { type: 'component', title: 'CircleInformationFilled', name: 'CircleInformationFilledIcon' },
          { type: 'component', title: 'CircleCloseFilled', name: 'CircleCloseFilledIcon' },
          { type: 'component', title: 'CircleStarFilled', name: 'CircleStarFilledIcon' },
          { type: 'component', title: 'CircleSucceedFilled', name: 'CircleSucceedFilledIcon' },
          { type: 'component', title: 'CircleWarningFilled', name: 'CircleWarningFilledIcon' },
          { type: 'component', title: 'StarFilled', name: 'StarFilledIcon' },
          { type: 'component', title: 'CircleHelpFilled', name: 'CircleHelpFilledIcon' },
          { type: 'component', title: 'DisableFilled', name: 'DisableFilledIcon' },
          { type: 'component', title: 'WifiFilled', name: 'WifiFilledIcon' },
          { type: 'component', title: 'WifiCloseFilled', name: 'WifiCloseFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Action',
        title: 'Action',
        children: [
          { type: 'component', title: 'PinFilled', name: 'PinFilledIcon' },
          { type: 'component', title: 'ThumbDownFilled', name: 'ThumbDownFilledIcon' },
          { type: 'component', title: 'ClearFilled', name: 'ClearFilledIcon' },
          { type: 'component', title: 'MapLocationFilled', name: 'MapLocationFilledIcon' },
          { type: 'component', title: 'ViewOffFilled', name: 'ViewOffFilledIcon' },
          { type: 'component', title: 'EditFilled', name: 'EditFilledIcon' },
          { type: 'component', title: 'SendFilled', name: 'SendFilledIcon' },
          { type: 'component', title: 'MoveUpFilled', name: 'MoveUpFilledIcon' },
          { type: 'component', title: 'ThumbUpFilled', name: 'ThumbUpFilledIcon' },
          { type: 'component', title: 'PinPreFilled', name: 'PinPreFilledIcon' },
          { type: 'component', title: 'ViewFilled', name: 'ViewFilledIcon' },
          { type: 'component', title: 'FilterFilled', name: 'FilterFilledIcon' },
          { type: 'component', title: 'SearchFilled', name: 'SearchFilledIcon' },
          { type: 'component', title: 'UrgencyFilled', name: 'UrgencyFilledIcon' },
          { type: 'component', title: 'ClothesFilled', name: 'ClothesFilledIcon' },
          { type: 'component', title: 'MicrophoneFilled', name: 'MicrophoneFilledIcon' },
          { type: 'component', title: 'BatchAddFilled', name: 'BatchAddFilledIcon' },
          { type: 'component', title: 'PhoneFilled', name: 'PhoneFilledIcon' },
          { type: 'component', title: 'DecorateFilled', name: 'DecorateFilledIcon' },
          { type: 'component', title: 'CopyOneFilled', name: 'CopyOneFilledIcon' },
          { type: 'component', title: 'DeleteFilled', name: 'DeleteFilledIcon' },
          { type: 'component', title: 'PrintFilled', name: 'PrintFilledIcon' },
          { type: 'component', title: 'BatchCheckFilled', name: 'BatchCheckFilledIcon' },
          { type: 'component', title: 'CheckCorrectFilled', name: 'CheckCorrectFilledIcon' },
          { type: 'component', title: 'CheckDisabledFilled', name: 'CheckDisabledFilledIcon' },
          { type: 'component', title: 'CheckboxFilled', name: 'CheckboxFilledIcon' },
          { type: 'component', title: 'RadioUnselectedFilled', name: 'RadioUnselectedFilledIcon' },
          { type: 'component', title: 'RadioSelectedFilled', name: 'RadioSelectedFilledIcon' },
          { type: 'component', title: 'SaveFilled', name: 'SaveFilledIcon' },
          { type: 'component', title: 'SaveAsFilled', name: 'SaveAsFilledIcon' },
          { type: 'component', title: 'RollbackFilled', name: 'RollbackFilledIcon' },
          { type: 'component', title: 'SwerveFilled', name: 'SwerveFilledIcon' },
          { type: 'component', title: 'PasteFilled', name: 'PasteFilledIcon' },
          { type: 'component', title: 'FormatPainterFilled', name: 'FormatPainterFilledIcon' },
          { type: 'component', title: 'SettingFilled', name: 'SettingFilledIcon' },
          { type: 'component', title: 'SettingSearchFilled', name: 'SettingSearchFilledIcon' },
          { type: 'component', title: 'AddChatFilled', name: 'AddChatFilledIcon' },
          { type: 'component', title: 'AddChatTwoFilled', name: 'AddChatTwoFilledIcon' },
          { type: 'component', title: 'PowerFilled', name: 'PowerFilledIcon' },
          { type: 'component', title: 'InfuseOneFilled', name: 'InfuseOneFilledIcon' },
          { type: 'component', title: 'SubmitFilled', name: 'SubmitFilledIcon' },
          { type: 'component', title: 'ScanFilled', name: 'ScanFilledIcon' },
          { type: 'component', title: 'ControlFilled', name: 'ControlFilledIcon' },
          { type: 'component', title: 'TranslateFilled', name: 'TranslateFilledIcon' },
          { type: 'component', title: 'RefreshFilled', name: 'RefreshFilledIcon' },
          { type: 'component', title: 'RefreshDoingFilled', name: 'RefreshDoingFilledIcon' },
          { type: 'component', title: 'RefreshDoneFilled', name: 'RefreshDoneFilledIcon' },
          { type: 'component', title: 'ShareFilled', name: 'ShareFilledIcon' },
          { type: 'component', title: 'UploadingFilled', name: 'UploadingFilledIcon' },
          { type: 'component', title: 'ExportFilled', name: 'ExportFilledIcon' },
          { type: 'component', title: 'DownloadFilled', name: 'DownloadFilledIcon' },
          { type: 'component', title: 'InfuseTwoFilled', name: 'InfuseTwoFilledIcon' },
          { type: 'component', title: 'SwitchFilled', name: 'SwitchFilledIcon' },
          { type: 'component', title: 'ToTopFilled', name: 'ToTopFilledIcon' },
          { type: 'component', title: 'ToBottomFilled', name: 'ToBottomFilledIcon' },
          { type: 'component', title: 'MoveDownFilled', name: 'MoveDownFilledIcon' },
          { type: 'component', title: 'TopFilled', name: 'TopFilledIcon' },
          { type: 'component', title: 'UndoFilled', name: 'UndoFilledIcon' },
          { type: 'component', title: 'GotoFilled', name: 'GotoFilledIcon' },
          { type: 'component', title: 'AmountUpTwoFilled', name: 'AmountUpTwoFilledIcon' },
          { type: 'component', title: 'AmountDownTwoFilled', name: 'AmountDownTwoFilledIcon' },
          { type: 'component', title: 'AmountDownFilled', name: 'AmountDownFilledIcon' },
          { type: 'component', title: 'AmountUpFilled', name: 'AmountUpFilledIcon' },
          { type: 'component', title: 'SortFilterFilled', name: 'SortFilterFilledIcon' },
          { type: 'component', title: 'SortAToZFilled', name: 'SortAToZFilledIcon' },
          { type: 'component', title: 'LinkFilled', name: 'LinkFilledIcon' },
          { type: 'component', title: 'DragFilled', name: 'DragFilledIcon' },
          { type: 'component', title: 'UnlinkFilled', name: 'UnlinkFilledIcon' },
          { type: 'component', title: 'SortZToAFilled', name: 'SortZToAFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Control',
        title: 'Control',
        children: [
          { type: 'component', title: 'ScreenFullFilled', name: 'ScreenFullFilledIcon' },
          { type: 'component', title: 'ScreenOffFilled', name: 'ScreenOffFilledIcon' },
          { type: 'component', title: 'MoveFilled', name: 'MoveFilledIcon' },
          { type: 'component', title: 'PointerFilled', name: 'PointerFilledIcon' },
          { type: 'component', title: 'CoverageFilled', name: 'CoverageFilledIcon' },
          { type: 'component', title: 'SurfaceFrontFilled', name: 'SurfaceFrontFilledIcon' },
          { type: 'component', title: 'SurfaceTopFilled', name: 'SurfaceTopFilledIcon' },
          { type: 'component', title: 'SurfaceLeftFilled', name: 'SurfaceLeftFilledIcon' },
          { type: 'component', title: 'SurfaceRightFilled', name: 'SurfaceRightFilledIcon' },
          { type: 'component', title: 'FindFilled', name: 'FindFilledIcon' },
          { type: 'component', title: 'TextFilled', name: 'TextFilledIcon' },
          { type: 'component', title: 'TopAlignFilled', name: 'TopAlignFilledIcon' },
          { type: 'component', title: 'BottomAlignFilled', name: 'BottomAlignFilledIcon' },
          { type: 'component', title: 'LeftAlignFilled', name: 'LeftAlignFilledIcon' },
          { type: 'component', title: 'RightAlignFilled', name: 'RightAlignFilledIcon' },
          { type: 'component', title: 'BackSquareFilled', name: 'BackSquareFilledIcon' },
          { type: 'component', title: 'LeftSquareFilled', name: 'LeftSquareFilledIcon' },
          { type: 'component', title: 'RightSquareFilled', name: 'RightSquareFilledIcon' },
          { type: 'component', title: 'FrontSquareFilled', name: 'FrontSquareFilledIcon' },
          { type: 'component', title: 'CopyTwoFilled', name: 'CopyTwoFilledIcon' },
          { type: 'component', title: 'AdjustHightFilled', name: 'AdjustHightFilledIcon' },
          { type: 'component', title: 'HightLessenFilled', name: 'HightLessenFilledIcon' },
          { type: 'component', title: 'AdjustWidthFilled', name: 'AdjustWidthFilledIcon' },
          { type: 'component', title: 'VerticalSplitFilled', name: 'VerticalSplitFilledIcon' },
          { type: 'component', title: 'VerticalCenterFilled', name: 'VerticalCenterFilledIcon' },
          { type: 'component', title: 'CenterHorizontallyFilled', name: 'CenterHorizontallyFilledIcon' },
          { type: 'component', title: 'KeyboardFilled', name: 'KeyboardFilledIcon' },
          { type: 'component', title: 'ZoomOutFilled', name: 'ZoomOutFilledIcon' },
          { type: 'component', title: 'ZoomInFilled', name: 'ZoomInFilledIcon' },
          { type: 'component', title: 'VolumeFilled', name: 'VolumeFilledIcon' },
          { type: 'component', title: 'VolumeMuteFilled', name: 'VolumeMuteFilledIcon' },
          { type: 'component', title: 'VolumeUpFilled', name: 'VolumeUpFilledIcon' },
          { type: 'component', title: 'VolumeDownFilled', name: 'VolumeDownFilledIcon' },
          { type: 'component', title: 'PlayFilled', name: 'PlayFilledIcon' },
          { type: 'component', title: 'StopFilled', name: 'StopFilledIcon' },
          { type: 'component', title: 'SuspendFilled', name: 'SuspendFilledIcon' },
          { type: 'component', title: 'AlignTxtLeftFilled', name: 'AlignTxtLeftFilledIcon' },
          { type: 'component', title: 'AlignTxtRightFilled', name: 'AlignTxtRightFilledIcon' },
          { type: 'component', title: 'AlignTxtCenterFilled', name: 'AlignTxtCenterFilledIcon' },
          { type: 'component', title: 'DensityLFilled', name: 'DensityLFilledIcon' },
          { type: 'component', title: 'DensityMFilled', name: 'DensityMFilledIcon' },
          { type: 'component', title: 'DensitySFilled', name: 'DensitySFilledIcon' },
          { type: 'component', title: 'FitScreenFilled', name: 'FitScreenFilledIcon' },
          { type: 'component', title: 'AlignTxtBothFilled', name: 'AlignTxtBothFilledIcon' },
          { type: 'component', title: 'RotationLeftFilled', name: 'RotationLeftFilledIcon' },
          { type: 'component', title: 'RotationRightFilled', name: 'RotationRightFilledIcon' },
          { type: 'component', title: 'OneToOneFilled', name: 'OneToOneFilledIcon' },
          { type: 'component', title: 'RowHeightSFilled', name: 'RowHeightSFilledIcon' },
          { type: 'component', title: 'RowHeightMFilled', name: 'RowHeightMFilledIcon' },
          { type: 'component', title: 'RowHeightLFilled', name: 'RowHeightLFilledIcon' },
          { type: 'component', title: 'Clockwise90Filled', name: 'Clockwise90FilledIcon' },
          { type: 'component', title: 'Anticlockwise90Filled', name: 'Anticlockwise90FilledIcon' },
          { type: 'component', title: 'LinecapButtFilled', name: 'LinecapButtFilledIcon' },
          { type: 'component', title: 'LinecapSquareFilled', name: 'LinecapSquareFilledIcon' },
          { type: 'component', title: 'LinecapRoundFilled', name: 'LinecapRoundFilledIcon' },
          { type: 'component', title: 'LinejoinMiterFilled', name: 'LinejoinMiterFilledIcon' },
          { type: 'component', title: 'LinejoinBevelFilled', name: 'LinejoinBevelFilledIcon' },
          { type: 'component', title: 'LinejoinRoundFilled', name: 'LinejoinRoundFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Data',
        title: 'Data',
        children: [
          { type: 'component', title: 'LightningFilled', name: 'LightningFilledIcon' },
          { type: 'component', title: 'PieTwoFilled', name: 'PieTwoFilledIcon' },
          { type: 'component', title: 'DataFilled', name: 'DataFilledIcon' },
          { type: 'component', title: 'PercentFilled', name: 'PercentFilledIcon' },
          { type: 'component', title: 'LineChartFilled', name: 'LineChartFilledIcon' },
          { type: 'component', title: 'TreeFilled', name: 'TreeFilledIcon' },
          { type: 'component', title: 'ThermoDynamicFilled', name: 'ThermoDynamicFilledIcon' },
          { type: 'component', title: 'MeasureFilled', name: 'MeasureFilledIcon' },
          { type: 'component', title: 'CompilingFilled', name: 'CompilingFilledIcon' },
          { type: 'component', title: 'AreaChartFilled', name: 'AreaChartFilledIcon' },
          { type: 'component', title: 'BarFilled', name: 'BarFilledIcon' },
          { type: 'component', title: 'ColumnFilled', name: 'ColumnFilledIcon' },
          { type: 'component', title: 'ColumnLineFilled', name: 'ColumnLineFilledIcon' },
          { type: 'component', title: 'WordCloudFilled', name: 'WordCloudFilledIcon' },
          { type: 'component', title: 'TableFilled', name: 'TableFilledIcon' },
          { type: 'component', title: 'PieOneFilled', name: 'PieOneFilledIcon' },
          { type: 'component', title: 'AnnularFilled', name: 'AnnularFilledIcon' },
          { type: 'component', title: 'RadarChartFilled', name: 'RadarChartFilledIcon' },
          { type: 'component', title: 'DataScreenFilled', name: 'DataScreenFilledIcon' },
          { type: 'component', title: 'ConstituteFilled', name: 'ConstituteFilledIcon' },
          { type: 'component', title: 'DatabaseFilled', name: 'DatabaseFilledIcon' },
          { type: 'component', title: 'DecimalFilled', name: 'DecimalFilledIcon' },
          { type: 'component', title: 'ScatterDiagramFilled', name: 'ScatterDiagramFilledIcon' },
          { type: 'component', title: 'NumberFilled', name: 'NumberFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Common',
        title: 'Common',
        children: [
          { type: 'component', title: 'LockFilled', name: 'LockFilledIcon' },
          { type: 'component', title: 'UnlockFilled', name: 'UnlockFilledIcon' },
          { type: 'component', title: 'SandGlassFilled', name: 'SandGlassFilledIcon' },
          { type: 'component', title: 'TimeOneFilled', name: 'TimeOneFilledIcon' },
          { type: 'component', title: 'LeafFilled', name: 'LeafFilledIcon' },
          { type: 'component', title: 'PackingBoxFilled', name: 'PackingBoxFilledIcon' },
          { type: 'component', title: 'AmountYuanFilled', name: 'AmountYuanFilledIcon' },
          { type: 'component', title: 'PurseFilled', name: 'PurseFilledIcon' },
          { type: 'component', title: 'AmountDollarFilled', name: 'AmountDollarFilledIcon' },
          { type: 'component', title: 'DealFilled', name: 'DealFilledIcon' },
          { type: 'component', title: 'EducationFilled', name: 'EducationFilledIcon' },
          { type: 'component', title: 'ShoppingBagFilled', name: 'ShoppingBagFilledIcon' },
          { type: 'component', title: 'BasketFilled', name: 'BasketFilledIcon' },
          { type: 'component', title: 'BedFilled', name: 'BedFilledIcon' },
          { type: 'component', title: 'SoupFilled', name: 'SoupFilledIcon' },
          { type: 'component', title: 'RiceFilled', name: 'RiceFilledIcon' },
          { type: 'component', title: 'BbqFilled', name: 'BbqFilledIcon' },
          { type: 'component', title: 'CameraFilled', name: 'CameraFilledIcon' },
          { type: 'component', title: 'BarCodeFilled', name: 'BarCodeFilledIcon' },
          { type: 'component', title: 'HandShakeFilled', name: 'HandShakeFilledIcon' },
          { type: 'component', title: 'FlagFilled', name: 'FlagFilledIcon' },
          { type: 'component', title: 'MotorcycleFilled', name: 'MotorcycleFilledIcon' },
          { type: 'component', title: 'ShieldFilled', name: 'ShieldFilledIcon' },
          { type: 'component', title: 'VipFilled', name: 'VipFilledIcon' },
          { type: 'component', title: 'CalculatorFilled', name: 'CalculatorFilledIcon' },
          { type: 'component', title: 'HeavySnowFilled', name: 'HeavySnowFilledIcon' },
          { type: 'component', title: 'HazeFilled', name: 'HazeFilledIcon' },
          { type: 'component', title: 'SandFilled', name: 'SandFilledIcon' },
          { type: 'component', title: 'MusicFilled', name: 'MusicFilledIcon' },
          { type: 'component', title: 'PadFilled', name: 'PadFilledIcon' },
          { type: 'component', title: 'MobileFilled', name: 'MobileFilledIcon' },
          { type: 'component', title: 'ComputerFilled', name: 'ComputerFilledIcon' },
          { type: 'component', title: 'BuildingFilled', name: 'BuildingFilledIcon' },
          { type: 'component', title: 'FireFilled', name: 'FireFilledIcon' },
          { type: 'component', title: 'GiftFilled', name: 'GiftFilledIcon' },
          { type: 'component', title: 'LabelFilled', name: 'LabelFilledIcon' },
          { type: 'component', title: 'MapFilled', name: 'MapFilledIcon' },
          { type: 'component', title: 'LocationFilled', name: 'LocationFilledIcon' },
          { type: 'component', title: 'ParkFilled', name: 'ParkFilledIcon' },
          { type: 'component', title: 'HospitalFilled', name: 'HospitalFilledIcon' },
          { type: 'component', title: 'ChipsFilled', name: 'ChipsFilledIcon' },
          { type: 'component', title: 'EquipmentFilled', name: 'EquipmentFilledIcon' },
          { type: 'component', title: 'PlaceOrderFilled', name: 'PlaceOrderFilledIcon' },
          { type: 'component', title: 'ChefFilled', name: 'ChefFilledIcon' },
          { type: 'component', title: 'SunnyFilled', name: 'SunnyFilledIcon' },
          { type: 'component', title: 'CloudyFilled', name: 'CloudyFilledIcon' },
          { type: 'component', title: 'LightRainFilled', name: 'LightRainFilledIcon' },
          { type: 'component', title: 'HeavyRainFilled', name: 'HeavyRainFilledIcon' },
          { type: 'component', title: 'LightSnowFilled', name: 'LightSnowFilledIcon' },
          { type: 'component', title: 'OnlineGatewayFilled', name: 'OnlineGatewayFilledIcon' },
          { type: 'component', title: 'MonitoringFilled', name: 'MonitoringFilledIcon' },
          { type: 'component', title: 'BadgeNewFilled', name: 'BadgeNewFilledIcon' },
          { type: 'component', title: 'BadgePromotionFilled', name: 'BadgePromotionFilledIcon' },
          { type: 'component', title: 'ServiceFilled', name: 'ServiceFilledIcon' },
          { type: 'component', title: 'ShoppingCartFilled', name: 'ShoppingCartFilledIcon' },
          { type: 'component', title: 'CheckStandFilled', name: 'CheckStandFilledIcon' },
          { type: 'component', title: 'StoreFilled', name: 'StoreFilledIcon' },
          { type: 'component', title: 'HouseFilled', name: 'HouseFilledIcon' },
          { type: 'component', title: 'CalendarFilled', name: 'CalendarFilledIcon' },
          { type: 'component', title: 'StampFilled', name: 'StampFilledIcon' },
          { type: 'component', title: 'PictureFilled', name: 'PictureFilledIcon' },
          { type: 'component', title: 'PictureOffFilled', name: 'PictureOffFilledIcon' },
          { type: 'component', title: 'FolderFilled', name: 'FolderFilledIcon' },
          { type: 'component', title: 'QrCodeFilled', name: 'QrCodeFilledIcon' },
          { type: 'component', title: 'GatherFilled', name: 'GatherFilledIcon' },
          { type: 'component', title: 'PuzzleFilled', name: 'PuzzleFilledIcon' },
          { type: 'component', title: 'CommentsFilled', name: 'CommentsFilledIcon' },
          { type: 'component', title: 'CouponFilled', name: 'CouponFilledIcon' },
          { type: 'component', title: 'ListFilled', name: 'ListFilledIcon' },
          { type: 'component', title: 'TimeTwoFilled', name: 'TimeTwoFilledIcon' },
          { type: 'component', title: 'OclockFilled', name: 'OclockFilledIcon' },
          { type: 'component', title: 'OfflineGatewayFilled', name: 'OfflineGatewayFilledIcon' },
          { type: 'component', title: 'FolderFilesFilled', name: 'FolderFilesFilledIcon' },
          { type: 'component', title: 'EarthFilled', name: 'EarthFilledIcon' },
          { type: 'component', title: 'PushMgtFilled', name: 'PushMgtFilledIcon' },
          { type: 'component', title: 'EmailSendFilled', name: 'EmailSendFilledIcon' },
          { type: 'component', title: 'UserFilled', name: 'UserFilledIcon' },
          { type: 'component', title: 'UserCrowdFilled', name: 'UserCrowdFilledIcon' },
          { type: 'component', title: 'UserPortrayalFilled', name: 'UserPortrayalFilledIcon' },
          { type: 'component', title: 'UserBlackFilled', name: 'UserBlackFilledIcon' },
          { type: 'component', title: 'UserWhiteFilled', name: 'UserWhiteFilledIcon' },
          { type: 'component', title: 'UserSilenceFilled', name: 'UserSilenceFilledIcon' },
          { type: 'component', title: 'UserLikeFilled', name: 'UserLikeFilledIcon' },
          { type: 'component', title: 'UserLeaveFilled', name: 'UserLeaveFilledIcon' },
          { type: 'component', title: 'UserAllFilled', name: 'UserAllFilledIcon' },
          { type: 'component', title: 'UserNewFilled', name: 'UserNewFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Retail',
        title: 'Retail',
        children: [
          { type: 'component', title: 'ConsumeFilled', name: 'ConsumeFilledIcon' },
          { type: 'component', title: 'VipConsumeFilled', name: 'VipConsumeFilledIcon' },
          { type: 'component', title: 'RailFilled', name: 'RailFilledIcon' },
          { type: 'component', title: 'IntegralFilled', name: 'IntegralFilledIcon' },
          { type: 'component', title: 'IntegralDistributeFilled', name: 'IntegralDistributeFilledIcon' },
          { type: 'component', title: 'PickingFilled', name: 'PickingFilledIcon' },
          { type: 'component', title: 'DistributionFilled', name: 'DistributionFilledIcon' },
          { type: 'component', title: 'GoodsFilled', name: 'GoodsFilledIcon' },
          { type: 'component', title: 'WarehousePreFilled', name: 'WarehousePreFilledIcon' },
          { type: 'component', title: 'WarehouseFilled', name: 'WarehouseFilledIcon' },
          { type: 'component', title: 'InventoryFilled', name: 'InventoryFilledIcon' },
          { type: 'component', title: 'ReplenishmentFilled', name: 'ReplenishmentFilledIcon' },
          { type: 'component', title: 'PathFilled', name: 'PathFilledIcon' },
          { type: 'component', title: 'ShelfFilled', name: 'ShelfFilledIcon' },
          { type: 'component', title: 'ManagementFilled', name: 'ManagementFilledIcon' },
          { type: 'component', title: 'OvertimeFilled', name: 'OvertimeFilledIcon' },
          { type: 'component', title: 'ScaleFilled', name: 'ScaleFilledIcon' },
          { type: 'component', title: 'SalesReturnFilled', name: 'SalesReturnFilledIcon' },
          { type: 'component', title: 'ManagementStockoutFilled', name: 'ManagementStockoutFilledIcon' },
          { type: 'component', title: 'ShelfUpFilled', name: 'ShelfUpFilledIcon' },
          { type: 'component', title: 'ShelfDownFilled', name: 'ShelfDownFilledIcon' },
          { type: 'component', title: 'TimingShelfDownFilled', name: 'TimingShelfDownFilledIcon' },
          { type: 'component', title: 'ProcessModeFilled', name: 'ProcessModeFilledIcon' },
          { type: 'component', title: 'GoodsSearchFilled', name: 'GoodsSearchFilledIcon' },
          { type: 'component', title: 'PickingGuidanceFilled', name: 'PickingGuidanceFilledIcon' },
          { type: 'component', title: 'PickingPathFilled', name: 'PickingPathFilledIcon' },
          { type: 'component', title: 'OperationFilled', name: 'OperationFilledIcon' },
          { type: 'component', title: 'MarketingFilled', name: 'MarketingFilledIcon' },
          { type: 'component', title: 'WarehouseIntoFilled', name: 'WarehouseIntoFilledIcon' },
          { type: 'component', title: 'OutOfWarehouseFilled', name: 'OutOfWarehouseFilledIcon' },
          { type: 'component', title: 'MarketplaceFilled', name: 'MarketplaceFilledIcon' },
          { type: 'component', title: 'IncubatorFilled', name: 'IncubatorFilledIcon' },
          { type: 'component', title: 'ToggleWarehouseXFilled', name: 'ToggleWarehouseXFilledIcon' },
          { type: 'component', title: 'ToggleWarehouseYFilled', name: 'ToggleWarehouseYFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'File',
        title: 'File',
        children: [
          { type: 'component', title: 'FileCsvFilled', name: 'FileCsvFilledIcon' },
          { type: 'component', title: 'FileRarFilled', name: 'FileRarFilledIcon' },
          { type: 'component', title: 'FilePptFilled', name: 'FilePptFilledIcon' },
          { type: 'component', title: 'FilePdfFilled', name: 'FilePdfFilledIcon' },
          { type: 'component', title: 'FileMovFilled', name: 'FileMovFilledIcon' },
          { type: 'component', title: 'FileMp3Filled', name: 'FileMp3FilledIcon' },
          { type: 'component', title: 'FileJpgFilled', name: 'FileJpgFilledIcon' },
          { type: 'component', title: 'FileAviFilled', name: 'FileAviFilledIcon' },
          { type: 'component', title: 'FileTxtFilled', name: 'FileTxtFilledIcon' },
          { type: 'component', title: 'FileMp4Filled', name: 'FileMp4FilledIcon' },
          { type: 'component', title: 'FileDocFilled', name: 'FileDocFilledIcon' },
          { type: 'component', title: 'FileCdrFilled', name: 'FileCdrFilledIcon' },
          { type: 'component', title: 'FilePngFilled', name: 'FilePngFilledIcon' },
          { type: 'component', title: 'WorkOrderAppointmentFilled', name: 'WorkOrderAppointmentFilledIcon' },
          { type: 'component', title: 'WorkOrderCheckFilled', name: 'WorkOrderCheckFilledIcon' },
          { type: 'component', title: 'OrderFilled', name: 'OrderFilledIcon' },
          { type: 'component', title: 'OrderIntegralFilled', name: 'OrderIntegralFilledIcon' },
          { type: 'component', title: 'OrderAbnormalFilled', name: 'OrderAbnormalFilledIcon' },
          { type: 'component', title: 'OrderDoneFilled', name: 'OrderDoneFilledIcon' },
          { type: 'component', title: 'OrderEditFilled', name: 'OrderEditFilledIcon' },
          { type: 'component', title: 'FileZipFilled', name: 'FileZipFilledIcon' },
          { type: 'component', title: 'FileXlsFilled', name: 'FileXlsFilledIcon' },
          { type: 'component', title: 'WorkOrderAbnormalFilled', name: 'WorkOrderAbnormalFilledIcon' },
          { type: 'component', title: 'WorkingOddFilled', name: 'WorkingOddFilledIcon' },
          { type: 'component', title: 'ReportFilled', name: 'ReportFilledIcon' },
          { type: 'component', title: 'ContractFilled', name: 'ContractFilledIcon' },
          { type: 'component', title: 'OrderCloseFilled', name: 'OrderCloseFilledIcon' },
          { type: 'component', title: 'ContractExclamationFilled', name: 'ContractExclamationFilledIcon' },
          { type: 'component', title: 'ContractAcrossFilled', name: 'ContractAcrossFilledIcon' },
          { type: 'component', title: 'WorkOrderFilled', name: 'WorkOrderFilledIcon' },
          { type: 'component', title: 'ComputerExclamationFilled', name: 'ComputerExclamationFilledIcon' },
          { type: 'component', title: 'ComputerAcrossFilled', name: 'ComputerAcrossFilledIcon' },
          { type: 'component', title: 'FileMovieFilled', name: 'FileMovieFilledIcon' },
          { type: 'component', title: 'WorkOrderInfoFilled', name: 'WorkOrderInfoFilledIcon' },
          { type: 'component', title: 'FileImportFilled', name: 'FileImportFilledIcon' },
          { type: 'component', title: 'FileExportFilled', name: 'FileExportFilledIcon' },
          { type: 'component', title: 'AttachmentsFilled', name: 'AttachmentsFilledIcon' },
        ],
      },
    ],
  },
]
